name: Docker Testing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-dockerfile:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Linting Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
